name: Build Ubuntu

on: [push]

jobs:
  ubuntu:
    name: Build & Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: sudo tools/debian-setup.sh --install-qt5-deps --install-deb-deps --install-optional --install-test-deps python3-pip -y
      - name: Mkdir
        run: mkdir build
      - name: Build debian pkg
        run: |
          ln --symbolic --no-dereference --force packaging/debian
          # Ignore changed symbols (on development branch).
          export DPKG_GENSYMBOLS_CHECK_LEVEL=0
          tools/make-version.py --set-release .
          export DEB_BUILD_OPTIONS="nocheck parallel=$(( $(getconf _NPROCESSORS_ONLN) + 2 ))"
          export DH_QUIET=1
          export MAKEFLAGS="--silent --coverage"
          export
          dpkg-buildpackage -b -us -uc -jauto
      - name: Move deb packages
        run: |
          mkdir deb
          mv ../*.deb deb
      - name: Upload deb packages
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: deb
